language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script:
  - nosetests
  - coverage run --source=preflyt -m nosetests
after_success:
  - coveralls
sudo: false
