language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script:
  - nosetests --with-coverage --cover-package=multilog
after_success:
  - coveralls
sudo: false
